name: news_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Application versioning: version_code+build_number
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0

  # Add more dependencies if needed, for example:
  # http: ^0.13.5
  # provider: ^6.0.0
  # flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # Enable Material icons for the app
  uses-material-design: true

  # Add your asset folder here
  assets:
    - lib/assets/

  # Optional: If you want to add custom fonts
  # fonts:
  #   - family: OpenSans
  #     fonts:
  #       - asset: fonts/OpenSans-Regular.ttf
  #       - asset: fonts/OpenSans-Bold.ttf
  #         weight: 700
